# Base configs
baseurl: "https://neildlr.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-XXXXXXXXX"

# UI configs
title: "Photography by Neil de la Rey"
subtitle: "See the world through my eyes!"
author: "Neil de la Rey"
header:
 title: "Photography"
 subtitle: "by Neil de la Rey"
footer:
 name: "Hi, my name is Neil"
 bio: "I am a photographer with a passion for landscape and wildlife. I enjoy sharing the beauty that I see in the world"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/neildelarey/"
  linkedin: "https://www.linkedin.com/in/neil-de-la-rey-a7685a72/"
  github: "https://www.github.com/neildlr"
